title: Subagya Perera
logo: https://github.com/nsubagya/subagya_perera_portfolio/blob/main/assets/Image00442%20(1)-modified.png?raw=true
#description: text below image
show_downloads: true
theme: jekyll-theme-minimal
